// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/mesh/mesh.proto

package mesh

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeshService_JoinNetwork_FullMethodName            = "/aegisray.mesh.MeshService/JoinNetwork"
	MeshService_LeaveNetwork_FullMethodName           = "/aegisray.mesh.MeshService/LeaveNetwork"
	MeshService_Heartbeat_FullMethodName              = "/aegisray.mesh.MeshService/Heartbeat"
	MeshService_DiscoverPeers_FullMethodName          = "/aegisray.mesh.MeshService/DiscoverPeers"
	MeshService_RequestIntroduction_FullMethodName    = "/aegisray.mesh.MeshService/RequestIntroduction"
	MeshService_SendPacket_FullMethodName             = "/aegisray.mesh.MeshService/SendPacket"
	MeshService_StreamPackets_FullMethodName          = "/aegisray.mesh.MeshService/StreamPackets"
	MeshService_AdvertiseRoutes_FullMethodName        = "/aegisray.mesh.MeshService/AdvertiseRoutes"
	MeshService_RequestRoutes_FullMethodName          = "/aegisray.mesh.MeshService/RequestRoutes"
	MeshService_InitiateHolePunch_FullMethodName      = "/aegisray.mesh.MeshService/InitiateHolePunch"
	MeshService_ExchangeConnectionInfo_FullMethodName = "/aegisray.mesh.MeshService/ExchangeConnectionInfo"
)

// MeshServiceClient is the client API for MeshService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MeshService handles mesh network operations
type MeshServiceClient interface {
	// Peer management
	JoinNetwork(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	LeaveNetwork(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Peer discovery
	DiscoverPeers(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error)
	RequestIntroduction(ctx context.Context, in *IntroductionRequest, opts ...grpc.CallOption) (*IntroductionResponse, error)
	// Data transmission
	SendPacket(ctx context.Context, in *PacketRequest, opts ...grpc.CallOption) (*PacketResponse, error)
	StreamPackets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamPacket, StreamPacket], error)
	// Route management
	AdvertiseRoutes(ctx context.Context, in *RouteAdvertisement, opts ...grpc.CallOption) (*RouteResponse, error)
	RequestRoutes(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error)
	// NAT traversal
	InitiateHolePunch(ctx context.Context, in *HolePunchRequest, opts ...grpc.CallOption) (*HolePunchResponse, error)
	ExchangeConnectionInfo(ctx context.Context, in *ConnectionInfoRequest, opts ...grpc.CallOption) (*ConnectionInfoResponse, error)
}

type meshServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeshServiceClient(cc grpc.ClientConnInterface) MeshServiceClient {
	return &meshServiceClient{cc}
}

func (c *meshServiceClient) JoinNetwork(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, MeshService_JoinNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) LeaveNetwork(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveResponse)
	err := c.cc.Invoke(ctx, MeshService_LeaveNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, MeshService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) DiscoverPeers(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoveryResponse)
	err := c.cc.Invoke(ctx, MeshService_DiscoverPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) RequestIntroduction(ctx context.Context, in *IntroductionRequest, opts ...grpc.CallOption) (*IntroductionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntroductionResponse)
	err := c.cc.Invoke(ctx, MeshService_RequestIntroduction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) SendPacket(ctx context.Context, in *PacketRequest, opts ...grpc.CallOption) (*PacketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PacketResponse)
	err := c.cc.Invoke(ctx, MeshService_SendPacket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) StreamPackets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamPacket, StreamPacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MeshService_ServiceDesc.Streams[0], MeshService_StreamPackets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPacket, StreamPacket]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeshService_StreamPacketsClient = grpc.BidiStreamingClient[StreamPacket, StreamPacket]

func (c *meshServiceClient) AdvertiseRoutes(ctx context.Context, in *RouteAdvertisement, opts ...grpc.CallOption) (*RouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteResponse)
	err := c.cc.Invoke(ctx, MeshService_AdvertiseRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) RequestRoutes(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteResponse)
	err := c.cc.Invoke(ctx, MeshService_RequestRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) InitiateHolePunch(ctx context.Context, in *HolePunchRequest, opts ...grpc.CallOption) (*HolePunchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HolePunchResponse)
	err := c.cc.Invoke(ctx, MeshService_InitiateHolePunch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) ExchangeConnectionInfo(ctx context.Context, in *ConnectionInfoRequest, opts ...grpc.CallOption) (*ConnectionInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectionInfoResponse)
	err := c.cc.Invoke(ctx, MeshService_ExchangeConnectionInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeshServiceServer is the server API for MeshService service.
// All implementations must embed UnimplementedMeshServiceServer
// for forward compatibility.
//
// MeshService handles mesh network operations
type MeshServiceServer interface {
	// Peer management
	JoinNetwork(context.Context, *JoinRequest) (*JoinResponse, error)
	LeaveNetwork(context.Context, *LeaveRequest) (*LeaveResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Peer discovery
	DiscoverPeers(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error)
	RequestIntroduction(context.Context, *IntroductionRequest) (*IntroductionResponse, error)
	// Data transmission
	SendPacket(context.Context, *PacketRequest) (*PacketResponse, error)
	StreamPackets(grpc.BidiStreamingServer[StreamPacket, StreamPacket]) error
	// Route management
	AdvertiseRoutes(context.Context, *RouteAdvertisement) (*RouteResponse, error)
	RequestRoutes(context.Context, *RouteRequest) (*RouteResponse, error)
	// NAT traversal
	InitiateHolePunch(context.Context, *HolePunchRequest) (*HolePunchResponse, error)
	ExchangeConnectionInfo(context.Context, *ConnectionInfoRequest) (*ConnectionInfoResponse, error)
	mustEmbedUnimplementedMeshServiceServer()
}

// UnimplementedMeshServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeshServiceServer struct{}

func (UnimplementedMeshServiceServer) JoinNetwork(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinNetwork not implemented")
}
func (UnimplementedMeshServiceServer) LeaveNetwork(context.Context, *LeaveRequest) (*LeaveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveNetwork not implemented")
}
func (UnimplementedMeshServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedMeshServiceServer) DiscoverPeers(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverPeers not implemented")
}
func (UnimplementedMeshServiceServer) RequestIntroduction(context.Context, *IntroductionRequest) (*IntroductionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestIntroduction not implemented")
}
func (UnimplementedMeshServiceServer) SendPacket(context.Context, *PacketRequest) (*PacketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPacket not implemented")
}
func (UnimplementedMeshServiceServer) StreamPackets(grpc.BidiStreamingServer[StreamPacket, StreamPacket]) error {
	return status.Error(codes.Unimplemented, "method StreamPackets not implemented")
}
func (UnimplementedMeshServiceServer) AdvertiseRoutes(context.Context, *RouteAdvertisement) (*RouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdvertiseRoutes not implemented")
}
func (UnimplementedMeshServiceServer) RequestRoutes(context.Context, *RouteRequest) (*RouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestRoutes not implemented")
}
func (UnimplementedMeshServiceServer) InitiateHolePunch(context.Context, *HolePunchRequest) (*HolePunchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateHolePunch not implemented")
}
func (UnimplementedMeshServiceServer) ExchangeConnectionInfo(context.Context, *ConnectionInfoRequest) (*ConnectionInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeConnectionInfo not implemented")
}
func (UnimplementedMeshServiceServer) mustEmbedUnimplementedMeshServiceServer() {}
func (UnimplementedMeshServiceServer) testEmbeddedByValue()                     {}

// UnsafeMeshServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeshServiceServer will
// result in compilation errors.
type UnsafeMeshServiceServer interface {
	mustEmbedUnimplementedMeshServiceServer()
}

func RegisterMeshServiceServer(s grpc.ServiceRegistrar, srv MeshServiceServer) {
	// If the following call panics, it indicates UnimplementedMeshServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeshService_ServiceDesc, srv)
}

func _MeshService_JoinNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).JoinNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_JoinNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).JoinNetwork(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_LeaveNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).LeaveNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_LeaveNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).LeaveNetwork(ctx, req.(*LeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_DiscoverPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).DiscoverPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_DiscoverPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).DiscoverPeers(ctx, req.(*DiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_RequestIntroduction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntroductionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).RequestIntroduction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_RequestIntroduction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).RequestIntroduction(ctx, req.(*IntroductionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_SendPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PacketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).SendPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_SendPacket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).SendPacket(ctx, req.(*PacketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_StreamPackets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MeshServiceServer).StreamPackets(&grpc.GenericServerStream[StreamPacket, StreamPacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MeshService_StreamPacketsServer = grpc.BidiStreamingServer[StreamPacket, StreamPacket]

func _MeshService_AdvertiseRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteAdvertisement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).AdvertiseRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_AdvertiseRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).AdvertiseRoutes(ctx, req.(*RouteAdvertisement))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_RequestRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).RequestRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_RequestRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).RequestRoutes(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_InitiateHolePunch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HolePunchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).InitiateHolePunch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_InitiateHolePunch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).InitiateHolePunch(ctx, req.(*HolePunchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_ExchangeConnectionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).ExchangeConnectionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_ExchangeConnectionInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).ExchangeConnectionInfo(ctx, req.(*ConnectionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeshService_ServiceDesc is the grpc.ServiceDesc for MeshService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeshService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegisray.mesh.MeshService",
	HandlerType: (*MeshServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinNetwork",
			Handler:    _MeshService_JoinNetwork_Handler,
		},
		{
			MethodName: "LeaveNetwork",
			Handler:    _MeshService_LeaveNetwork_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _MeshService_Heartbeat_Handler,
		},
		{
			MethodName: "DiscoverPeers",
			Handler:    _MeshService_DiscoverPeers_Handler,
		},
		{
			MethodName: "RequestIntroduction",
			Handler:    _MeshService_RequestIntroduction_Handler,
		},
		{
			MethodName: "SendPacket",
			Handler:    _MeshService_SendPacket_Handler,
		},
		{
			MethodName: "AdvertiseRoutes",
			Handler:    _MeshService_AdvertiseRoutes_Handler,
		},
		{
			MethodName: "RequestRoutes",
			Handler:    _MeshService_RequestRoutes_Handler,
		},
		{
			MethodName: "InitiateHolePunch",
			Handler:    _MeshService_InitiateHolePunch_Handler,
		},
		{
			MethodName: "ExchangeConnectionInfo",
			Handler:    _MeshService_ExchangeConnectionInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPackets",
			Handler:       _MeshService_StreamPackets_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/mesh/mesh.proto",
}
