// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/mesh/mesh.proto

package mesh

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type PacketType int32

const (
	PacketType_DATA                PacketType = 0
	PacketType_CONTROL             PacketType = 1
	PacketType_HEARTBEAT           PacketType = 2
	PacketType_KEY_EXCHANGE        PacketType = 3
	PacketType_ROUTE_ADVERTISEMENT PacketType = 4
	PacketType_NAT_TRAVERSAL       PacketType = 5
)

// Enum value maps for PacketType.
var (
	PacketType_name = map[int32]string{
		0: "DATA",
		1: "CONTROL",
		2: "HEARTBEAT",
		3: "KEY_EXCHANGE",
		4: "ROUTE_ADVERTISEMENT",
		5: "NAT_TRAVERSAL",
	}
	PacketType_value = map[string]int32{
		"DATA":                0,
		"CONTROL":             1,
		"HEARTBEAT":           2,
		"KEY_EXCHANGE":        3,
		"ROUTE_ADVERTISEMENT": 4,
		"NAT_TRAVERSAL":       5,
	}
)

func (x PacketType) Enum() *PacketType {
	p := new(PacketType)
	*p = x
	return p
}

func (x PacketType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mesh_mesh_proto_enumTypes[0].Descriptor()
}

func (PacketType) Type() protoreflect.EnumType {
	return &file_proto_mesh_mesh_proto_enumTypes[0]
}

func (x PacketType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketType.Descriptor instead.
func (PacketType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{0}
}

type PeerUpdateType int32

const (
	PeerUpdateType_PEER_JOINED       PeerUpdateType = 0
	PeerUpdateType_PEER_LEFT         PeerUpdateType = 1
	PeerUpdateType_PEER_UPDATED      PeerUpdateType = 2
	PeerUpdateType_PEER_CONNECTED    PeerUpdateType = 3
	PeerUpdateType_PEER_DISCONNECTED PeerUpdateType = 4
)

// Enum value maps for PeerUpdateType.
var (
	PeerUpdateType_name = map[int32]string{
		0: "PEER_JOINED",
		1: "PEER_LEFT",
		2: "PEER_UPDATED",
		3: "PEER_CONNECTED",
		4: "PEER_DISCONNECTED",
	}
	PeerUpdateType_value = map[string]int32{
		"PEER_JOINED":       0,
		"PEER_LEFT":         1,
		"PEER_UPDATED":      2,
		"PEER_CONNECTED":    3,
		"PEER_DISCONNECTED": 4,
	}
)

func (x PeerUpdateType) Enum() *PeerUpdateType {
	p := new(PeerUpdateType)
	*p = x
	return p
}

func (x PeerUpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerUpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mesh_mesh_proto_enumTypes[1].Descriptor()
}

func (PeerUpdateType) Type() protoreflect.EnumType {
	return &file_proto_mesh_mesh_proto_enumTypes[1]
}

func (x PeerUpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerUpdateType.Descriptor instead.
func (PeerUpdateType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{1}
}

type RouteUpdateType int32

const (
	RouteUpdateType_ROUTE_ADDED   RouteUpdateType = 0
	RouteUpdateType_ROUTE_REMOVED RouteUpdateType = 1
	RouteUpdateType_ROUTE_UPDATED RouteUpdateType = 2
)

// Enum value maps for RouteUpdateType.
var (
	RouteUpdateType_name = map[int32]string{
		0: "ROUTE_ADDED",
		1: "ROUTE_REMOVED",
		2: "ROUTE_UPDATED",
	}
	RouteUpdateType_value = map[string]int32{
		"ROUTE_ADDED":   0,
		"ROUTE_REMOVED": 1,
		"ROUTE_UPDATED": 2,
	}
)

func (x RouteUpdateType) Enum() *RouteUpdateType {
	p := new(RouteUpdateType)
	*p = x
	return p
}

func (x RouteUpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteUpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mesh_mesh_proto_enumTypes[2].Descriptor()
}

func (RouteUpdateType) Type() protoreflect.EnumType {
	return &file_proto_mesh_mesh_proto_enumTypes[2]
}

func (x RouteUpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteUpdateType.Descriptor instead.
func (RouteUpdateType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{2}
}

type RouteType int32

const (
	RouteType_DIRECT     RouteType = 0
	RouteType_SUBNET     RouteType = 1
	RouteType_EXIT_NODE  RouteType = 2
	RouteType_ADVERTISED RouteType = 3
)

// Enum value maps for RouteType.
var (
	RouteType_name = map[int32]string{
		0: "DIRECT",
		1: "SUBNET",
		2: "EXIT_NODE",
		3: "ADVERTISED",
	}
	RouteType_value = map[string]int32{
		"DIRECT":     0,
		"SUBNET":     1,
		"EXIT_NODE":  2,
		"ADVERTISED": 3,
	}
)

func (x RouteType) Enum() *RouteType {
	p := new(RouteType)
	*p = x
	return p
}

func (x RouteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mesh_mesh_proto_enumTypes[3].Descriptor()
}

func (RouteType) Type() protoreflect.EnumType {
	return &file_proto_mesh_mesh_proto_enumTypes[3]
}

func (x RouteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteType.Descriptor instead.
func (RouteType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{3}
}

type NATType int32

const (
	NATType_UNKNOWN         NATType = 0
	NATType_NONE            NATType = 1 // Direct connection possible
	NATType_FULL_CONE       NATType = 2 // Easy traversal
	NATType_RESTRICTED_CONE NATType = 3 // Moderate traversal
	NATType_PORT_RESTRICTED NATType = 4 // Hard traversal
	NATType_SYMMETRIC       NATType = 5 // Very hard traversal
)

// Enum value maps for NATType.
var (
	NATType_name = map[int32]string{
		0: "UNKNOWN",
		1: "NONE",
		2: "FULL_CONE",
		3: "RESTRICTED_CONE",
		4: "PORT_RESTRICTED",
		5: "SYMMETRIC",
	}
	NATType_value = map[string]int32{
		"UNKNOWN":         0,
		"NONE":            1,
		"FULL_CONE":       2,
		"RESTRICTED_CONE": 3,
		"PORT_RESTRICTED": 4,
		"SYMMETRIC":       5,
	}
)

func (x NATType) Enum() *NATType {
	p := new(NATType)
	*p = x
	return p
}

func (x NATType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NATType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_mesh_mesh_proto_enumTypes[4].Descriptor()
}

func (NATType) Type() protoreflect.EnumType {
	return &file_proto_mesh_mesh_proto_enumTypes[4]
}

func (x NATType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NATType.Descriptor instead.
func (NATType) EnumDescriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{4}
}

// Network join/leave messages
type JoinRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey      string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MeshIp         string                 `protobuf:"bytes,3,opt,name=mesh_ip,json=meshIp,proto3" json:"mesh_ip,omitempty"`
	AllowedIps     []string               `protobuf:"bytes,4,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	ConnectionInfo *ConnectionInfo        `protobuf:"bytes,5,opt,name=connection_info,json=connectionInfo,proto3" json:"connection_info,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NetworkName    string                 `protobuf:"bytes,7,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	Signature      string                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"` // Cryptographic signature
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *JoinRequest) GetMeshIp() string {
	if x != nil {
		return x.MeshIp
	}
	return ""
}

func (x *JoinRequest) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *JoinRequest) GetConnectionInfo() *ConnectionInfo {
	if x != nil {
		return x.ConnectionInfo
	}
	return nil
}

func (x *JoinRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *JoinRequest) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *JoinRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AssignedIp    string                 `protobuf:"bytes,2,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`
	Peers         []*PeerInfo            `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	NetworkInfo   *NetworkInfo           `protobuf:"bytes,4,opt,name=network_info,json=networkInfo,proto3" json:"network_info,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinResponse) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *JoinResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *JoinResponse) GetNetworkInfo() *NetworkInfo {
	if x != nil {
		return x.NetworkInfo
	}
	return nil
}

func (x *JoinResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRequest) Reset() {
	*x = LeaveRequest{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRequest) ProtoMessage() {}

func (x *LeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRequest.ProtoReflect.Descriptor instead.
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LeaveRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *LeaveRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LeaveRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type LeaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveResponse) Reset() {
	*x = LeaveResponse{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveResponse) ProtoMessage() {}

func (x *LeaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveResponse.ProtoReflect.Descriptor instead.
func (*LeaveResponse) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *LeaveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Heartbeat messages
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        *NodeStatus            `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() *NodeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	PeerUpdates   []*PeerUpdate          `protobuf:"bytes,2,rep,name=peer_updates,json=peerUpdates,proto3" json:"peer_updates,omitempty"`
	RouteUpdates  []*RouteUpdate         `protobuf:"bytes,3,rep,name=route_updates,json=routeUpdates,proto3" json:"route_updates,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *HeartbeatResponse) GetPeerUpdates() []*PeerUpdate {
	if x != nil {
		return x.PeerUpdates
	}
	return nil
}

func (x *HeartbeatResponse) GetRouteUpdates() []*RouteUpdate {
	if x != nil {
		return x.RouteUpdates
	}
	return nil
}

func (x *HeartbeatResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Peer discovery messages
type DiscoveryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NetworkName      string                 `protobuf:"bytes,2,opt,name=network_name,json=networkName,proto3" json:"network_name,omitempty"`
	MaxPeers         int32                  `protobuf:"varint,3,opt,name=max_peers,json=maxPeers,proto3" json:"max_peers,omitempty"`
	PreferredRegions []string               `protobuf:"bytes,4,rep,name=preferred_regions,json=preferredRegions,proto3" json:"preferred_regions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{6}
}

func (x *DiscoveryRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DiscoveryRequest) GetNetworkName() string {
	if x != nil {
		return x.NetworkName
	}
	return ""
}

func (x *DiscoveryRequest) GetMaxPeers() int32 {
	if x != nil {
		return x.MaxPeers
	}
	return 0
}

func (x *DiscoveryRequest) GetPreferredRegions() []string {
	if x != nil {
		return x.PreferredRegions
	}
	return nil
}

type DiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	NetworkInfo   *NetworkInfo           `protobuf:"bytes,2,opt,name=network_info,json=networkInfo,proto3" json:"network_info,omitempty"`
	TotalPeers    int32                  `protobuf:"varint,3,opt,name=total_peers,json=totalPeers,proto3" json:"total_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{7}
}

func (x *DiscoveryResponse) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *DiscoveryResponse) GetNetworkInfo() *NetworkInfo {
	if x != nil {
		return x.NetworkInfo
	}
	return nil
}

func (x *DiscoveryResponse) GetTotalPeers() int32 {
	if x != nil {
		return x.TotalPeers
	}
	return 0
}

type IntroductionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntroductionRequest) Reset() {
	*x = IntroductionRequest{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntroductionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntroductionRequest) ProtoMessage() {}

func (x *IntroductionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntroductionRequest.ProtoReflect.Descriptor instead.
func (*IntroductionRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{8}
}

func (x *IntroductionRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *IntroductionRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *IntroductionRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IntroductionRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type IntroductionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TargetConnection *ConnectionInfo        `protobuf:"bytes,2,opt,name=target_connection,json=targetConnection,proto3" json:"target_connection,omitempty"`
	SessionToken     string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	ExpiresAt        int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IntroductionResponse) Reset() {
	*x = IntroductionResponse{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntroductionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntroductionResponse) ProtoMessage() {}

func (x *IntroductionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntroductionResponse.ProtoReflect.Descriptor instead.
func (*IntroductionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{9}
}

func (x *IntroductionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IntroductionResponse) GetTargetConnection() *ConnectionInfo {
	if x != nil {
		return x.TargetConnection
	}
	return nil
}

func (x *IntroductionResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *IntroductionResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

// Data transmission messages
type PacketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	DestId        string                 `protobuf:"bytes,3,opt,name=dest_id,json=destId,proto3" json:"dest_id,omitempty"`
	EncryptedData []byte                 `protobuf:"bytes,4,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	PacketType    PacketType             `protobuf:"varint,5,opt,name=packet_type,json=packetType,proto3,enum=aegisray.mesh.PacketType" json:"packet_type,omitempty"`
	PacketId      uint32                 `protobuf:"varint,6,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      *PacketMetadata        `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketRequest) Reset() {
	*x = PacketRequest{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketRequest) ProtoMessage() {}

func (x *PacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketRequest.ProtoReflect.Descriptor instead.
func (*PacketRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{10}
}

func (x *PacketRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PacketRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *PacketRequest) GetDestId() string {
	if x != nil {
		return x.DestId
	}
	return ""
}

func (x *PacketRequest) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *PacketRequest) GetPacketType() PacketType {
	if x != nil {
		return x.PacketType
	}
	return PacketType_DATA
}

func (x *PacketRequest) GetPacketId() uint32 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

func (x *PacketRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PacketRequest) GetMetadata() *PacketMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PacketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PacketId      uint32                 `protobuf:"varint,2,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	ResponseData  []byte                 `protobuf:"bytes,3,opt,name=response_data,json=responseData,proto3" json:"response_data,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketResponse) Reset() {
	*x = PacketResponse{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketResponse) ProtoMessage() {}

func (x *PacketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketResponse.ProtoReflect.Descriptor instead.
func (*PacketResponse) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{11}
}

func (x *PacketResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PacketResponse) GetPacketId() uint32 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

func (x *PacketResponse) GetResponseData() []byte {
	if x != nil {
		return x.ResponseData
	}
	return nil
}

func (x *PacketResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PacketResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StreamPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Sequence      uint32                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	IsControl     bool                   `protobuf:"varint,4,opt,name=is_control,json=isControl,proto3" json:"is_control,omitempty"`
	Metadata      *PacketMetadata        `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPacket) Reset() {
	*x = StreamPacket{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPacket) ProtoMessage() {}

func (x *StreamPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPacket.ProtoReflect.Descriptor instead.
func (*StreamPacket) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{12}
}

func (x *StreamPacket) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamPacket) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *StreamPacket) GetIsControl() bool {
	if x != nil {
		return x.IsControl
	}
	return false
}

func (x *StreamPacket) GetMetadata() *PacketMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Route management messages
type RouteAdvertisement struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Routes         []*Route               `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	SequenceNumber uint32                 `protobuf:"varint,3,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature      string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RouteAdvertisement) Reset() {
	*x = RouteAdvertisement{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteAdvertisement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteAdvertisement) ProtoMessage() {}

func (x *RouteAdvertisement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteAdvertisement.ProtoReflect.Descriptor instead.
func (*RouteAdvertisement) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{13}
}

func (x *RouteAdvertisement) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RouteAdvertisement) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RouteAdvertisement) GetSequenceNumber() uint32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *RouteAdvertisement) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RouteAdvertisement) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type RouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Destinations  []string               `protobuf:"bytes,2,rep,name=destinations,proto3" json:"destinations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{14}
}

func (x *RouteRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RouteRequest) GetDestinations() []string {
	if x != nil {
		return x.Destinations
	}
	return nil
}

type RouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Routes        []*Route               `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{15}
}

func (x *RouteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RouteResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *RouteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// NAT traversal messages
type HolePunchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	RequesterInfo *ConnectionInfo        `protobuf:"bytes,3,opt,name=requester_info,json=requesterInfo,proto3" json:"requester_info,omitempty"`
	SessionToken  string                 `protobuf:"bytes,4,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HolePunchRequest) Reset() {
	*x = HolePunchRequest{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolePunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolePunchRequest) ProtoMessage() {}

func (x *HolePunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolePunchRequest.ProtoReflect.Descriptor instead.
func (*HolePunchRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{16}
}

func (x *HolePunchRequest) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *HolePunchRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *HolePunchRequest) GetRequesterInfo() *ConnectionInfo {
	if x != nil {
		return x.RequesterInfo
	}
	return nil
}

func (x *HolePunchRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type HolePunchResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TargetInfo     *ConnectionInfo        `protobuf:"bytes,2,opt,name=target_info,json=targetInfo,proto3" json:"target_info,omitempty"`
	PunchAddresses []string               `protobuf:"bytes,3,rep,name=punch_addresses,json=punchAddresses,proto3" json:"punch_addresses,omitempty"`
	PunchPort      int32                  `protobuf:"varint,4,opt,name=punch_port,json=punchPort,proto3" json:"punch_port,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HolePunchResponse) Reset() {
	*x = HolePunchResponse{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolePunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolePunchResponse) ProtoMessage() {}

func (x *HolePunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolePunchResponse.ProtoReflect.Descriptor instead.
func (*HolePunchResponse) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{17}
}

func (x *HolePunchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HolePunchResponse) GetTargetInfo() *ConnectionInfo {
	if x != nil {
		return x.TargetInfo
	}
	return nil
}

func (x *HolePunchResponse) GetPunchAddresses() []string {
	if x != nil {
		return x.PunchAddresses
	}
	return nil
}

func (x *HolePunchResponse) GetPunchPort() int32 {
	if x != nil {
		return x.PunchPort
	}
	return 0
}

type ConnectionInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LocalInfo     *ConnectionInfo        `protobuf:"bytes,2,opt,name=local_info,json=localInfo,proto3" json:"local_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionInfoRequest) Reset() {
	*x = ConnectionInfoRequest{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInfoRequest) ProtoMessage() {}

func (x *ConnectionInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInfoRequest.ProtoReflect.Descriptor instead.
func (*ConnectionInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{18}
}

func (x *ConnectionInfoRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ConnectionInfoRequest) GetLocalInfo() *ConnectionInfo {
	if x != nil {
		return x.LocalInfo
	}
	return nil
}

type ConnectionInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicInfo    *ConnectionInfo        `protobuf:"bytes,3,opt,name=public_info,json=publicInfo,proto3" json:"public_info,omitempty"`
	NatType       NATType                `protobuf:"varint,4,opt,name=nat_type,json=natType,proto3,enum=aegisray.mesh.NATType" json:"nat_type,omitempty"`
	StunServers   []string               `protobuf:"bytes,5,rep,name=stun_servers,json=stunServers,proto3" json:"stun_servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionInfoResponse) Reset() {
	*x = ConnectionInfoResponse{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInfoResponse) ProtoMessage() {}

func (x *ConnectionInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInfoResponse.ProtoReflect.Descriptor instead.
func (*ConnectionInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{19}
}

func (x *ConnectionInfoResponse) GetPublicInfo() *ConnectionInfo {
	if x != nil {
		return x.PublicInfo
	}
	return nil
}

func (x *ConnectionInfoResponse) GetNatType() NATType {
	if x != nil {
		return x.NatType
	}
	return NATType_UNKNOWN
}

func (x *ConnectionInfoResponse) GetStunServers() []string {
	if x != nil {
		return x.StunServers
	}
	return nil
}

// Data structures
type PeerInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey      string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	MeshIp         string                 `protobuf:"bytes,3,opt,name=mesh_ip,json=meshIp,proto3" json:"mesh_ip,omitempty"`
	AllowedIps     []string               `protobuf:"bytes,4,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	ConnectionInfo *ConnectionInfo        `protobuf:"bytes,5,opt,name=connection_info,json=connectionInfo,proto3" json:"connection_info,omitempty"`
	LastSeen       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Status         *NodeStatus            `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Region         string                 `protobuf:"bytes,8,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{20}
}

func (x *PeerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeerInfo) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerInfo) GetMeshIp() string {
	if x != nil {
		return x.MeshIp
	}
	return ""
}

func (x *PeerInfo) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *PeerInfo) GetConnectionInfo() *ConnectionInfo {
	if x != nil {
		return x.ConnectionInfo
	}
	return nil
}

func (x *PeerInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *PeerInfo) GetStatus() *NodeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PeerInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type ConnectionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicAddress string                 `protobuf:"bytes,1,opt,name=public_address,json=publicAddress,proto3" json:"public_address,omitempty"`
	LocalAddress  string                 `protobuf:"bytes,2,opt,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	NatType       NATType                `protobuf:"varint,4,opt,name=nat_type,json=natType,proto3,enum=aegisray.mesh.NATType" json:"nat_type,omitempty"`
	StunResults   []string               `protobuf:"bytes,5,rep,name=stun_results,json=stunResults,proto3" json:"stun_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionInfo) Reset() {
	*x = ConnectionInfo{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionInfo) ProtoMessage() {}

func (x *ConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionInfo.ProtoReflect.Descriptor instead.
func (*ConnectionInfo) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{21}
}

func (x *ConnectionInfo) GetPublicAddress() string {
	if x != nil {
		return x.PublicAddress
	}
	return ""
}

func (x *ConnectionInfo) GetLocalAddress() string {
	if x != nil {
		return x.LocalAddress
	}
	return ""
}

func (x *ConnectionInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ConnectionInfo) GetNatType() NATType {
	if x != nil {
		return x.NatType
	}
	return NATType_UNKNOWN
}

func (x *ConnectionInfo) GetStunResults() []string {
	if x != nil {
		return x.StunResults
	}
	return nil
}

type NetworkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cidr          string                 `protobuf:"bytes,2,opt,name=cidr,proto3" json:"cidr,omitempty"`
	DnsServers    []string               `protobuf:"bytes,3,rep,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty"`
	TotalNodes    int32                  `protobuf:"varint,4,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{22}
}

func (x *NetworkInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInfo) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *NetworkInfo) GetDnsServers() []string {
	if x != nil {
		return x.DnsServers
	}
	return nil
}

func (x *NetworkInfo) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *NetworkInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type NodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerCount     int32                  `protobuf:"varint,1,opt,name=peer_count,json=peerCount,proto3" json:"peer_count,omitempty"`
	CpuUsage      float64                `protobuf:"fixed64,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	BytesSent     int64                  `protobuf:"varint,4,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived int64                  `protobuf:"varint,5,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Version       string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,8,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{23}
}

func (x *NodeStatus) GetPeerCount() int32 {
	if x != nil {
		return x.PeerCount
	}
	return 0
}

func (x *NodeStatus) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *NodeStatus) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *NodeStatus) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *NodeStatus) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *NodeStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *NodeStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeStatus) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type PeerUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PeerUpdateType         `protobuf:"varint,1,opt,name=type,proto3,enum=aegisray.mesh.PeerUpdateType" json:"type,omitempty"`
	Peer          *PeerInfo              `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerUpdate) Reset() {
	*x = PeerUpdate{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerUpdate) ProtoMessage() {}

func (x *PeerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerUpdate.ProtoReflect.Descriptor instead.
func (*PeerUpdate) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{24}
}

func (x *PeerUpdate) GetType() PeerUpdateType {
	if x != nil {
		return x.Type
	}
	return PeerUpdateType_PEER_JOINED
}

func (x *PeerUpdate) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *PeerUpdate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PeerUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type RouteUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          RouteUpdateType        `protobuf:"varint,1,opt,name=type,proto3,enum=aegisray.mesh.RouteUpdateType" json:"type,omitempty"`
	Route         *Route                 `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	Advertiser    string                 `protobuf:"bytes,3,opt,name=advertiser,proto3" json:"advertiser,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteUpdate) Reset() {
	*x = RouteUpdate{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUpdate) ProtoMessage() {}

func (x *RouteUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUpdate.ProtoReflect.Descriptor instead.
func (*RouteUpdate) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{25}
}

func (x *RouteUpdate) GetType() RouteUpdateType {
	if x != nil {
		return x.Type
	}
	return RouteUpdateType_ROUTE_ADDED
}

func (x *RouteUpdate) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *RouteUpdate) GetAdvertiser() string {
	if x != nil {
		return x.Advertiser
	}
	return ""
}

func (x *RouteUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	NextHop       string                 `protobuf:"bytes,2,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	Metric        int32                  `protobuf:"varint,3,opt,name=metric,proto3" json:"metric,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RouteType     RouteType              `protobuf:"varint,5,opt,name=route_type,json=routeType,proto3,enum=aegisray.mesh.RouteType" json:"route_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{26}
}

func (x *Route) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Route) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

func (x *Route) GetMetric() int32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

func (x *Route) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Route) GetRouteType() RouteType {
	if x != nil {
		return x.RouteType
	}
	return RouteType_DIRECT
}

type PacketMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttl           int32                  `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	SourceRegion  string                 `protobuf:"bytes,2,opt,name=source_region,json=sourceRegion,proto3" json:"source_region,omitempty"`
	DestRegion    string                 `protobuf:"bytes,3,opt,name=dest_region,json=destRegion,proto3" json:"dest_region,omitempty"`
	Path          []string               `protobuf:"bytes,4,rep,name=path,proto3" json:"path,omitempty"` // Nodes the packet has traversed
	Fragmented    bool                   `protobuf:"varint,5,opt,name=fragmented,proto3" json:"fragmented,omitempty"`
	FragmentId    int32                  `protobuf:"varint,6,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketMetadata) Reset() {
	*x = PacketMetadata{}
	mi := &file_proto_mesh_mesh_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketMetadata) ProtoMessage() {}

func (x *PacketMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_mesh_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketMetadata.ProtoReflect.Descriptor instead.
func (*PacketMetadata) Descriptor() ([]byte, []int) {
	return file_proto_mesh_mesh_proto_rawDescGZIP(), []int{27}
}

func (x *PacketMetadata) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *PacketMetadata) GetSourceRegion() string {
	if x != nil {
		return x.SourceRegion
	}
	return ""
}

func (x *PacketMetadata) GetDestRegion() string {
	if x != nil {
		return x.DestRegion
	}
	return ""
}

func (x *PacketMetadata) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *PacketMetadata) GetFragmented() bool {
	if x != nil {
		return x.Fragmented
	}
	return false
}

func (x *PacketMetadata) GetFragmentId() int32 {
	if x != nil {
		return x.FragmentId
	}
	return 0
}

var File_proto_mesh_mesh_proto protoreflect.FileDescriptor

const file_proto_mesh_mesh_proto_rawDesc = "" +
	"\n" +
	"\x15proto/mesh/mesh.proto\x12\raegisray.mesh\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x02\n" +
	"\vJoinRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x17\n" +
	"\amesh_ip\x18\x03 \x01(\tR\x06meshIp\x12\x1f\n" +
	"\vallowed_ips\x18\x04 \x03(\tR\n" +
	"allowedIps\x12F\n" +
	"\x0fconnection_info\x18\x05 \x01(\v2\x1d.aegisray.mesh.ConnectionInfoR\x0econnectionInfo\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\fnetwork_name\x18\a \x01(\tR\vnetworkName\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\"\xcd\x01\n" +
	"\fJoinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vassigned_ip\x18\x02 \x01(\tR\n" +
	"assignedIp\x12-\n" +
	"\x05peers\x18\x03 \x03(\v2\x17.aegisray.mesh.PeerInfoR\x05peers\x12=\n" +
	"\fnetwork_info\x18\x04 \x01(\v2\x1a.aegisray.mesh.NetworkInfoR\vnetworkInfo\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x97\x01\n" +
	"\fLeaveRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\"C\n" +
	"\rLeaveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x98\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x121\n" +
	"\x06status\x18\x02 \x01(\v2\x19.aegisray.mesh.NodeStatusR\x06status\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xe2\x01\n" +
	"\x11HeartbeatResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12<\n" +
	"\fpeer_updates\x18\x02 \x03(\v2\x19.aegisray.mesh.PeerUpdateR\vpeerUpdates\x12?\n" +
	"\rroute_updates\x18\x03 \x03(\v2\x1a.aegisray.mesh.RouteUpdateR\frouteUpdates\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x98\x01\n" +
	"\x10DiscoveryRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fnetwork_name\x18\x02 \x01(\tR\vnetworkName\x12\x1b\n" +
	"\tmax_peers\x18\x03 \x01(\x05R\bmaxPeers\x12+\n" +
	"\x11preferred_regions\x18\x04 \x03(\tR\x10preferredRegions\"\xa2\x01\n" +
	"\x11DiscoveryResponse\x12-\n" +
	"\x05peers\x18\x01 \x03(\v2\x17.aegisray.mesh.PeerInfoR\x05peers\x12=\n" +
	"\fnetwork_info\x18\x02 \x01(\v2\x1a.aegisray.mesh.NetworkInfoR\vnetworkInfo\x12\x1f\n" +
	"\vtotal_peers\x18\x03 \x01(\x05R\n" +
	"totalPeers\"\xa9\x01\n" +
	"\x13IntroductionRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xc0\x01\n" +
	"\x14IntroductionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12J\n" +
	"\x11target_connection\x18\x02 \x01(\v2\x1d.aegisray.mesh.ConnectionInfoR\x10targetConnection\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"\xd9\x02\n" +
	"\rPacketRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x17\n" +
	"\adest_id\x18\x03 \x01(\tR\x06destId\x12%\n" +
	"\x0eencrypted_data\x18\x04 \x01(\fR\rencryptedData\x12:\n" +
	"\vpacket_type\x18\x05 \x01(\x0e2\x19.aegisray.mesh.PacketTypeR\n" +
	"packetType\x12\x1b\n" +
	"\tpacket_id\x18\x06 \x01(\rR\bpacketId\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x129\n" +
	"\bmetadata\x18\b \x01(\v2\x1d.aegisray.mesh.PacketMetadataR\bmetadata\"\xbc\x01\n" +
	"\x0ePacketResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tpacket_id\x18\x02 \x01(\rR\bpacketId\x12#\n" +
	"\rresponse_data\x18\x03 \x01(\fR\fresponseData\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xb7\x01\n" +
	"\fStreamPacket\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\rR\bsequence\x12\x1d\n" +
	"\n" +
	"is_control\x18\x04 \x01(\bR\tisControl\x129\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1d.aegisray.mesh.PacketMetadataR\bmetadata\"\xdc\x01\n" +
	"\x12RouteAdvertisement\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12,\n" +
	"\x06routes\x18\x02 \x03(\v2\x14.aegisray.mesh.RouteR\x06routes\x12'\n" +
	"\x0fsequence_number\x18\x03 \x01(\rR\x0esequenceNumber\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\"K\n" +
	"\fRouteRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\"\n" +
	"\fdestinations\x18\x02 \x03(\tR\fdestinations\"m\n" +
	"\rRouteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x06routes\x18\x02 \x03(\v2\x14.aegisray.mesh.RouteR\x06routes\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xbd\x01\n" +
	"\x10HolePunchRequest\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12D\n" +
	"\x0erequester_info\x18\x03 \x01(\v2\x1d.aegisray.mesh.ConnectionInfoR\rrequesterInfo\x12#\n" +
	"\rsession_token\x18\x04 \x01(\tR\fsessionToken\"\xb5\x01\n" +
	"\x11HolePunchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12>\n" +
	"\vtarget_info\x18\x02 \x01(\v2\x1d.aegisray.mesh.ConnectionInfoR\n" +
	"targetInfo\x12'\n" +
	"\x0fpunch_addresses\x18\x03 \x03(\tR\x0epunchAddresses\x12\x1d\n" +
	"\n" +
	"punch_port\x18\x04 \x01(\x05R\tpunchPort\"n\n" +
	"\x15ConnectionInfoRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12<\n" +
	"\n" +
	"local_info\x18\x02 \x01(\v2\x1d.aegisray.mesh.ConnectionInfoR\tlocalInfo\"\xae\x01\n" +
	"\x16ConnectionInfoResponse\x12>\n" +
	"\vpublic_info\x18\x03 \x01(\v2\x1d.aegisray.mesh.ConnectionInfoR\n" +
	"publicInfo\x121\n" +
	"\bnat_type\x18\x04 \x01(\x0e2\x16.aegisray.mesh.NATTypeR\anatType\x12!\n" +
	"\fstun_servers\x18\x05 \x03(\tR\vstunServers\"\xbf\x02\n" +
	"\bPeerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x17\n" +
	"\amesh_ip\x18\x03 \x01(\tR\x06meshIp\x12\x1f\n" +
	"\vallowed_ips\x18\x04 \x03(\tR\n" +
	"allowedIps\x12F\n" +
	"\x0fconnection_info\x18\x05 \x01(\v2\x1d.aegisray.mesh.ConnectionInfoR\x0econnectionInfo\x127\n" +
	"\tlast_seen\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x121\n" +
	"\x06status\x18\a \x01(\v2\x19.aegisray.mesh.NodeStatusR\x06status\x12\x16\n" +
	"\x06region\x18\b \x01(\tR\x06region\"\xc6\x01\n" +
	"\x0eConnectionInfo\x12%\n" +
	"\x0epublic_address\x18\x01 \x01(\tR\rpublicAddress\x12#\n" +
	"\rlocal_address\x18\x02 \x01(\tR\flocalAddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x121\n" +
	"\bnat_type\x18\x04 \x01(\x0e2\x16.aegisray.mesh.NATTypeR\anatType\x12!\n" +
	"\fstun_results\x18\x05 \x03(\tR\vstunResults\"\x91\x01\n" +
	"\vNetworkInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04cidr\x18\x02 \x01(\tR\x04cidr\x12\x1f\n" +
	"\vdns_servers\x18\x03 \x03(\tR\n" +
	"dnsServers\x12\x1f\n" +
	"\vtotal_nodes\x18\x04 \x01(\x05R\n" +
	"totalNodes\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"\x96\x02\n" +
	"\n" +
	"NodeStatus\x12\x1d\n" +
	"\n" +
	"peer_count\x18\x01 \x01(\x05R\tpeerCount\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x03 \x01(\x01R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x04 \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x05 \x01(\x03R\rbytesReceived\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x03R\ruptimeSeconds\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\b \x03(\tR\fcapabilities\"\xbe\x01\n" +
	"\n" +
	"PeerUpdate\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.aegisray.mesh.PeerUpdateTypeR\x04type\x12+\n" +
	"\x04peer\x18\x02 \x01(\v2\x17.aegisray.mesh.PeerInfoR\x04peer\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xc7\x01\n" +
	"\vRouteUpdate\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.aegisray.mesh.RouteUpdateTypeR\x04type\x12*\n" +
	"\x05route\x18\x02 \x01(\v2\x14.aegisray.mesh.RouteR\x05route\x12\x1e\n" +
	"\n" +
	"advertiser\x18\x03 \x01(\tR\n" +
	"advertiser\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xd0\x01\n" +
	"\x05Route\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x12\x19\n" +
	"\bnext_hop\x18\x02 \x01(\tR\anextHop\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\x05R\x06metric\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x127\n" +
	"\n" +
	"route_type\x18\x05 \x01(\x0e2\x18.aegisray.mesh.RouteTypeR\trouteType\"\xbd\x01\n" +
	"\x0ePacketMetadata\x12\x10\n" +
	"\x03ttl\x18\x01 \x01(\x05R\x03ttl\x12#\n" +
	"\rsource_region\x18\x02 \x01(\tR\fsourceRegion\x12\x1f\n" +
	"\vdest_region\x18\x03 \x01(\tR\n" +
	"destRegion\x12\x12\n" +
	"\x04path\x18\x04 \x03(\tR\x04path\x12\x1e\n" +
	"\n" +
	"fragmented\x18\x05 \x01(\bR\n" +
	"fragmented\x12\x1f\n" +
	"\vfragment_id\x18\x06 \x01(\x05R\n" +
	"fragmentId*p\n" +
	"\n" +
	"PacketType\x12\b\n" +
	"\x04DATA\x10\x00\x12\v\n" +
	"\aCONTROL\x10\x01\x12\r\n" +
	"\tHEARTBEAT\x10\x02\x12\x10\n" +
	"\fKEY_EXCHANGE\x10\x03\x12\x17\n" +
	"\x13ROUTE_ADVERTISEMENT\x10\x04\x12\x11\n" +
	"\rNAT_TRAVERSAL\x10\x05*m\n" +
	"\x0ePeerUpdateType\x12\x0f\n" +
	"\vPEER_JOINED\x10\x00\x12\r\n" +
	"\tPEER_LEFT\x10\x01\x12\x10\n" +
	"\fPEER_UPDATED\x10\x02\x12\x12\n" +
	"\x0ePEER_CONNECTED\x10\x03\x12\x15\n" +
	"\x11PEER_DISCONNECTED\x10\x04*H\n" +
	"\x0fRouteUpdateType\x12\x0f\n" +
	"\vROUTE_ADDED\x10\x00\x12\x11\n" +
	"\rROUTE_REMOVED\x10\x01\x12\x11\n" +
	"\rROUTE_UPDATED\x10\x02*B\n" +
	"\tRouteType\x12\n" +
	"\n" +
	"\x06DIRECT\x10\x00\x12\n" +
	"\n" +
	"\x06SUBNET\x10\x01\x12\r\n" +
	"\tEXIT_NODE\x10\x02\x12\x0e\n" +
	"\n" +
	"ADVERTISED\x10\x03*h\n" +
	"\aNATType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04NONE\x10\x01\x12\r\n" +
	"\tFULL_CONE\x10\x02\x12\x13\n" +
	"\x0fRESTRICTED_CONE\x10\x03\x12\x13\n" +
	"\x0fPORT_RESTRICTED\x10\x04\x12\r\n" +
	"\tSYMMETRIC\x10\x052\x9d\a\n" +
	"\vMeshService\x12F\n" +
	"\vJoinNetwork\x12\x1a.aegisray.mesh.JoinRequest\x1a\x1b.aegisray.mesh.JoinResponse\x12I\n" +
	"\fLeaveNetwork\x12\x1b.aegisray.mesh.LeaveRequest\x1a\x1c.aegisray.mesh.LeaveResponse\x12N\n" +
	"\tHeartbeat\x12\x1f.aegisray.mesh.HeartbeatRequest\x1a .aegisray.mesh.HeartbeatResponse\x12R\n" +
	"\rDiscoverPeers\x12\x1f.aegisray.mesh.DiscoveryRequest\x1a .aegisray.mesh.DiscoveryResponse\x12^\n" +
	"\x13RequestIntroduction\x12\".aegisray.mesh.IntroductionRequest\x1a#.aegisray.mesh.IntroductionResponse\x12I\n" +
	"\n" +
	"SendPacket\x12\x1c.aegisray.mesh.PacketRequest\x1a\x1d.aegisray.mesh.PacketResponse\x12M\n" +
	"\rStreamPackets\x12\x1b.aegisray.mesh.StreamPacket\x1a\x1b.aegisray.mesh.StreamPacket(\x010\x01\x12R\n" +
	"\x0fAdvertiseRoutes\x12!.aegisray.mesh.RouteAdvertisement\x1a\x1c.aegisray.mesh.RouteResponse\x12J\n" +
	"\rRequestRoutes\x12\x1b.aegisray.mesh.RouteRequest\x1a\x1c.aegisray.mesh.RouteResponse\x12V\n" +
	"\x11InitiateHolePunch\x12\x1f.aegisray.mesh.HolePunchRequest\x1a .aegisray.mesh.HolePunchResponse\x12e\n" +
	"\x16ExchangeConnectionInfo\x12$.aegisray.mesh.ConnectionInfoRequest\x1a%.aegisray.mesh.ConnectionInfoResponseB+Z)github.com/aegisray/vpn-tunnel/proto/meshb\x06proto3"

var (
	file_proto_mesh_mesh_proto_rawDescOnce sync.Once
	file_proto_mesh_mesh_proto_rawDescData []byte
)

func file_proto_mesh_mesh_proto_rawDescGZIP() []byte {
	file_proto_mesh_mesh_proto_rawDescOnce.Do(func() {
		file_proto_mesh_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mesh_mesh_proto_rawDesc), len(file_proto_mesh_mesh_proto_rawDesc)))
	})
	return file_proto_mesh_mesh_proto_rawDescData
}

var file_proto_mesh_mesh_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_mesh_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_mesh_mesh_proto_goTypes = []any{
	(PacketType)(0),                // 0: aegisray.mesh.PacketType
	(PeerUpdateType)(0),            // 1: aegisray.mesh.PeerUpdateType
	(RouteUpdateType)(0),           // 2: aegisray.mesh.RouteUpdateType
	(RouteType)(0),                 // 3: aegisray.mesh.RouteType
	(NATType)(0),                   // 4: aegisray.mesh.NATType
	(*JoinRequest)(nil),            // 5: aegisray.mesh.JoinRequest
	(*JoinResponse)(nil),           // 6: aegisray.mesh.JoinResponse
	(*LeaveRequest)(nil),           // 7: aegisray.mesh.LeaveRequest
	(*LeaveResponse)(nil),          // 8: aegisray.mesh.LeaveResponse
	(*HeartbeatRequest)(nil),       // 9: aegisray.mesh.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 10: aegisray.mesh.HeartbeatResponse
	(*DiscoveryRequest)(nil),       // 11: aegisray.mesh.DiscoveryRequest
	(*DiscoveryResponse)(nil),      // 12: aegisray.mesh.DiscoveryResponse
	(*IntroductionRequest)(nil),    // 13: aegisray.mesh.IntroductionRequest
	(*IntroductionResponse)(nil),   // 14: aegisray.mesh.IntroductionResponse
	(*PacketRequest)(nil),          // 15: aegisray.mesh.PacketRequest
	(*PacketResponse)(nil),         // 16: aegisray.mesh.PacketResponse
	(*StreamPacket)(nil),           // 17: aegisray.mesh.StreamPacket
	(*RouteAdvertisement)(nil),     // 18: aegisray.mesh.RouteAdvertisement
	(*RouteRequest)(nil),           // 19: aegisray.mesh.RouteRequest
	(*RouteResponse)(nil),          // 20: aegisray.mesh.RouteResponse
	(*HolePunchRequest)(nil),       // 21: aegisray.mesh.HolePunchRequest
	(*HolePunchResponse)(nil),      // 22: aegisray.mesh.HolePunchResponse
	(*ConnectionInfoRequest)(nil),  // 23: aegisray.mesh.ConnectionInfoRequest
	(*ConnectionInfoResponse)(nil), // 24: aegisray.mesh.ConnectionInfoResponse
	(*PeerInfo)(nil),               // 25: aegisray.mesh.PeerInfo
	(*ConnectionInfo)(nil),         // 26: aegisray.mesh.ConnectionInfo
	(*NetworkInfo)(nil),            // 27: aegisray.mesh.NetworkInfo
	(*NodeStatus)(nil),             // 28: aegisray.mesh.NodeStatus
	(*PeerUpdate)(nil),             // 29: aegisray.mesh.PeerUpdate
	(*RouteUpdate)(nil),            // 30: aegisray.mesh.RouteUpdate
	(*Route)(nil),                  // 31: aegisray.mesh.Route
	(*PacketMetadata)(nil),         // 32: aegisray.mesh.PacketMetadata
	(*timestamppb.Timestamp)(nil),  // 33: google.protobuf.Timestamp
}
var file_proto_mesh_mesh_proto_depIdxs = []int32{
	26, // 0: aegisray.mesh.JoinRequest.connection_info:type_name -> aegisray.mesh.ConnectionInfo
	33, // 1: aegisray.mesh.JoinRequest.timestamp:type_name -> google.protobuf.Timestamp
	25, // 2: aegisray.mesh.JoinResponse.peers:type_name -> aegisray.mesh.PeerInfo
	27, // 3: aegisray.mesh.JoinResponse.network_info:type_name -> aegisray.mesh.NetworkInfo
	33, // 4: aegisray.mesh.LeaveRequest.timestamp:type_name -> google.protobuf.Timestamp
	28, // 5: aegisray.mesh.HeartbeatRequest.status:type_name -> aegisray.mesh.NodeStatus
	33, // 6: aegisray.mesh.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	29, // 7: aegisray.mesh.HeartbeatResponse.peer_updates:type_name -> aegisray.mesh.PeerUpdate
	30, // 8: aegisray.mesh.HeartbeatResponse.route_updates:type_name -> aegisray.mesh.RouteUpdate
	33, // 9: aegisray.mesh.HeartbeatResponse.timestamp:type_name -> google.protobuf.Timestamp
	25, // 10: aegisray.mesh.DiscoveryResponse.peers:type_name -> aegisray.mesh.PeerInfo
	27, // 11: aegisray.mesh.DiscoveryResponse.network_info:type_name -> aegisray.mesh.NetworkInfo
	33, // 12: aegisray.mesh.IntroductionRequest.timestamp:type_name -> google.protobuf.Timestamp
	26, // 13: aegisray.mesh.IntroductionResponse.target_connection:type_name -> aegisray.mesh.ConnectionInfo
	0,  // 14: aegisray.mesh.PacketRequest.packet_type:type_name -> aegisray.mesh.PacketType
	33, // 15: aegisray.mesh.PacketRequest.timestamp:type_name -> google.protobuf.Timestamp
	32, // 16: aegisray.mesh.PacketRequest.metadata:type_name -> aegisray.mesh.PacketMetadata
	33, // 17: aegisray.mesh.PacketResponse.timestamp:type_name -> google.protobuf.Timestamp
	32, // 18: aegisray.mesh.StreamPacket.metadata:type_name -> aegisray.mesh.PacketMetadata
	31, // 19: aegisray.mesh.RouteAdvertisement.routes:type_name -> aegisray.mesh.Route
	33, // 20: aegisray.mesh.RouteAdvertisement.timestamp:type_name -> google.protobuf.Timestamp
	31, // 21: aegisray.mesh.RouteResponse.routes:type_name -> aegisray.mesh.Route
	26, // 22: aegisray.mesh.HolePunchRequest.requester_info:type_name -> aegisray.mesh.ConnectionInfo
	26, // 23: aegisray.mesh.HolePunchResponse.target_info:type_name -> aegisray.mesh.ConnectionInfo
	26, // 24: aegisray.mesh.ConnectionInfoRequest.local_info:type_name -> aegisray.mesh.ConnectionInfo
	26, // 25: aegisray.mesh.ConnectionInfoResponse.public_info:type_name -> aegisray.mesh.ConnectionInfo
	4,  // 26: aegisray.mesh.ConnectionInfoResponse.nat_type:type_name -> aegisray.mesh.NATType
	26, // 27: aegisray.mesh.PeerInfo.connection_info:type_name -> aegisray.mesh.ConnectionInfo
	33, // 28: aegisray.mesh.PeerInfo.last_seen:type_name -> google.protobuf.Timestamp
	28, // 29: aegisray.mesh.PeerInfo.status:type_name -> aegisray.mesh.NodeStatus
	4,  // 30: aegisray.mesh.ConnectionInfo.nat_type:type_name -> aegisray.mesh.NATType
	1,  // 31: aegisray.mesh.PeerUpdate.type:type_name -> aegisray.mesh.PeerUpdateType
	25, // 32: aegisray.mesh.PeerUpdate.peer:type_name -> aegisray.mesh.PeerInfo
	33, // 33: aegisray.mesh.PeerUpdate.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 34: aegisray.mesh.RouteUpdate.type:type_name -> aegisray.mesh.RouteUpdateType
	31, // 35: aegisray.mesh.RouteUpdate.route:type_name -> aegisray.mesh.Route
	33, // 36: aegisray.mesh.RouteUpdate.timestamp:type_name -> google.protobuf.Timestamp
	33, // 37: aegisray.mesh.Route.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 38: aegisray.mesh.Route.route_type:type_name -> aegisray.mesh.RouteType
	5,  // 39: aegisray.mesh.MeshService.JoinNetwork:input_type -> aegisray.mesh.JoinRequest
	7,  // 40: aegisray.mesh.MeshService.LeaveNetwork:input_type -> aegisray.mesh.LeaveRequest
	9,  // 41: aegisray.mesh.MeshService.Heartbeat:input_type -> aegisray.mesh.HeartbeatRequest
	11, // 42: aegisray.mesh.MeshService.DiscoverPeers:input_type -> aegisray.mesh.DiscoveryRequest
	13, // 43: aegisray.mesh.MeshService.RequestIntroduction:input_type -> aegisray.mesh.IntroductionRequest
	15, // 44: aegisray.mesh.MeshService.SendPacket:input_type -> aegisray.mesh.PacketRequest
	17, // 45: aegisray.mesh.MeshService.StreamPackets:input_type -> aegisray.mesh.StreamPacket
	18, // 46: aegisray.mesh.MeshService.AdvertiseRoutes:input_type -> aegisray.mesh.RouteAdvertisement
	19, // 47: aegisray.mesh.MeshService.RequestRoutes:input_type -> aegisray.mesh.RouteRequest
	21, // 48: aegisray.mesh.MeshService.InitiateHolePunch:input_type -> aegisray.mesh.HolePunchRequest
	23, // 49: aegisray.mesh.MeshService.ExchangeConnectionInfo:input_type -> aegisray.mesh.ConnectionInfoRequest
	6,  // 50: aegisray.mesh.MeshService.JoinNetwork:output_type -> aegisray.mesh.JoinResponse
	8,  // 51: aegisray.mesh.MeshService.LeaveNetwork:output_type -> aegisray.mesh.LeaveResponse
	10, // 52: aegisray.mesh.MeshService.Heartbeat:output_type -> aegisray.mesh.HeartbeatResponse
	12, // 53: aegisray.mesh.MeshService.DiscoverPeers:output_type -> aegisray.mesh.DiscoveryResponse
	14, // 54: aegisray.mesh.MeshService.RequestIntroduction:output_type -> aegisray.mesh.IntroductionResponse
	16, // 55: aegisray.mesh.MeshService.SendPacket:output_type -> aegisray.mesh.PacketResponse
	17, // 56: aegisray.mesh.MeshService.StreamPackets:output_type -> aegisray.mesh.StreamPacket
	20, // 57: aegisray.mesh.MeshService.AdvertiseRoutes:output_type -> aegisray.mesh.RouteResponse
	20, // 58: aegisray.mesh.MeshService.RequestRoutes:output_type -> aegisray.mesh.RouteResponse
	22, // 59: aegisray.mesh.MeshService.InitiateHolePunch:output_type -> aegisray.mesh.HolePunchResponse
	24, // 60: aegisray.mesh.MeshService.ExchangeConnectionInfo:output_type -> aegisray.mesh.ConnectionInfoResponse
	50, // [50:61] is the sub-list for method output_type
	39, // [39:50] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_proto_mesh_mesh_proto_init() }
func file_proto_mesh_mesh_proto_init() {
	if File_proto_mesh_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mesh_mesh_proto_rawDesc), len(file_proto_mesh_mesh_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mesh_mesh_proto_goTypes,
		DependencyIndexes: file_proto_mesh_mesh_proto_depIdxs,
		EnumInfos:         file_proto_mesh_mesh_proto_enumTypes,
		MessageInfos:      file_proto_mesh_mesh_proto_msgTypes,
	}.Build()
	File_proto_mesh_mesh_proto = out.File
	file_proto_mesh_mesh_proto_goTypes = nil
	file_proto_mesh_mesh_proto_depIdxs = nil
}
